# Write your query or mutation here
query GameWithReviews($gameId: Int!) {
  gameWithReviews(gameId: $gameId) {
    gameId
    gameName
    basePrice
    description
    releaseDate
    publisher {
      publisherName
    }
    categories {
      categoryId
      categoryName
    }
    retailers {
      retailerId
      retailerName
    }
    images {
      name
    }
    rating
    reviews {
      reviewId
      rating
      comment
      reviewer {
        userId
        username
      }
      votes {
        voteId
        isUpvote
        user {
          userId
          username
        }
      }
    }
  }
}
