# Write your query or mutation here
query GameWithReviews($gameId: Int!) {
  gameWithReviews(gameId: $gameId) {
    gameId
    gameName
    basePrice
    description
    publisher {
      publisherName
    }
    categories {
      categoryName
    }
    images {
      name
    }
    rating
    reviews {
      reviewId
      rating
      comment
      reviewer {
        userId
        username
      }
      votes {
        isUpvote
      }
    }
  }
}
