query AllGames {
  games {
    gameId
    gameName
    description
    basePrice
    releaseDate
    rating
    publisher {
      publisherId
      publisherName
    }
    categories {
      categoryId
      categoryName
    }
    retailers {
      retailerId
      retailerName
    }
    images {
      name
    }
  }
}